### PR TITLE
German language added

### PR DESCRIPTION
**Pull request by beckerr-rzht**
* Added l18n support using "locale"

* Added german translation

* Added support for country name as translation key for institution names
  Currently in use are "de", "en", "fr" and "nb".
  See:
  ```
  wget -qO - https://static.eduvpn.nl/disco/institute_access.json \
	| jq '.instances[].display_name' | awk -F: '/:/{print $1}' | sort -u
  ```

* Institution list is sorted after display name translation.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
hi @beckerr-rzht! Thanks for this pull request, great work! I never got the time to figure out how to do proper internationalisation, so this is of great use. To let you know, we are currently working on a complete rewrite, which will probably be merged in into this tree as 2.0 at some point:

https://github.com/gijzelaerr/pyeduvpn

Which is for now command line only. I'll see if I can port your changes to that tree (also).

**Comment by gijzelaerr** [comment]
hi @beckerr-rzht
sorry for the delay in processing this. Your contribution is highly valued, but we are still busy preparing the 2.0 release.

**Comment by gijzelaerr** [comment]
hi @beckerr-rzht, i don't understand what happened to this PR, I don't find the actual code that implements the localisation anymore. Do you understand what happened?

We are preparing the 2.0 release at the moment, and localisation is planned for 2.1. Would you be interested to help out with the german translation (again)? That would be beyond amazing!

**Comment by beckerr-rzht** [comment]
I have looked at the source code: It seems that some things have changed. Let's see what I can do.

Enclosed (and for documentation) the changes from then as a patch. 
[python-eduvpn-client-i18n.patch.gz](https://github.com/eduvpn/python-eduvpn-client/files/6147661/python-eduvpn-client-i18n.patch.gz)

**Comment by beckerr-rzht** [comment]
I've added a pull request for this. Please note the comments I made there. #341

**Pull request merged**
