### PR TITLE
Apply never-default if redirect-gateway is not defined

### PR DESCRIPTION
**Pull request by ghost**
This is what is working on my side to solve #167 !

### CODE REVIEW

**Comment by gijzelaerr** [comment]
thanks! We are investigating.

**Comment by Junonogis** [comment]
Honestly did no test on this, but my understanding is ovpn file is merged then parsed and provided as a hash to this method.

**Comment by gijzelaerr** [comment]
@Junonogis are you going to test this?

**Comment by fkooman** [comment]
I think the "best" way to really fix this is for NetworkManager-openvpn to implement support for this. The second best option is to expose this through the OAuth API.

I'd go for fixing this in NetworkManager-openvpn as this would also solve problems for many other users of NetworkManager-openvpn and doesn't require the API.

**Comment by gijzelaerr** [comment]
fixing `NetworkManager-openvpn` upstream? that would take years before it lands on all supported platforms right?

**Comment by gijzelaerr** [comment]
can do, will take a bit of work though since it would add a new screen to the interface.

**Comment by GeckoSplinter** [comment]
Hello guys any update on this ?

**Comment by gijzelaerr** [comment]
hi! sorry for the delay, I've been working on other projects. 

Luckily i've managed to allocate some time again for python-eduvpn-client in a couple of weeks, where i hope to solve all outstanding issues.

thanks!

**Comment by gijzelaerr** [comment]
@fkooman given the time/budget constraints, what do you think is the best way forward? Adding a settings screen is maybe better to do for a 2.0 release this summer. Would merging this PR interfere with other configurations?

**Comment by fkooman** [comment]
There's this now as well: https://github.com/eduvpn/documentation/blob/v2/API.md#profile-list The `default_gateway` option available through the API.

**Comment by gijzelaerr** [comment]
Thank you for your PR, but we are going to solve this issue in a different way for 2.x. Sorry for the long delay, but it looks like this is finally going to be addressed.

**Pull request closed without merging**
