### PR TITLE
Add integration test.

### PR DESCRIPTION
**Pull request by alvra**
Add an integration test that connects to an actual server, given as an environment variable.

### CODE REVIEW

**Comment by alvra** [comment]
For some reason, this fails when adding the new connection to NetworkManager.

**Review by gijzelaerr — COMMENTED** [review]
Isn't it required to set the username and password also?

i think it would be useful to update the docs developer section also to instruct how to run the test suite as a developer using these env vars.

**Comment by alvra** [comment]
The username and password are also set in the environment variable, in standard format: `TEST_SERVER=username:password@example.com`.

I've added an example in the developer docs.

**Comment by alvra** [comment]
The PR currently fails because it (looks like it) has no access to github secrets to run the added integration test.

**Pull request merged**
