### PR TITLE
Include client_id in phase 2

### PR DESCRIPTION
**Pull request by Junonogis**
We were experiencing a phase 2 "invalid_request".

This fixed this issue. I have no clue to check if is has any impact. Let me know your thougts.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
Hi! Thanks for the PR. What is the distribution name and version you are using? And how did you install the client?

**Comment by Junonogis** [comment]
I installed the client with pip3 from the master branch and I am personally using fedora 29, but we had same problem on recent Suse and Debian stretch.

On server-side :
```
ii  php-eduvpn-common                 1.3.2-1                        all          library for Let's Connect! VPN server components
ii  php-fkooman-oauth2-server         3.0.5-1                        all          simple OAuth 2.0 server
ii  php-fpm                           1:7.0+49                       all          server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
ii  php7.0-fpm                        7.0.30-0+deb9u1                amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  vpn-admin-portal                  1.7.3-1                        all          VPN Admin Portal for Let's Connect!
ii  vpn-server-api                    1.4.9-1                        all          VPN Server API for Let's Connect!
ii  vpn-server-node                   1.1.2-3                        all          Control a Let's Connect! VPN Server Node
ii  vpn-user-portal                   1.8.6-1                        all          VPN User Portal for Let's Connect!
```

**Comment by gijzelaerr** [comment]
I can replicate that with 
```
oauth==1.0.1              
oauthlib==3.0.0           
requests-oauthlib==1.2.0  
```
But it is weird, the oauth object is already constructed with this `client_id`, so the code should pick that up.

**Comment by gijzelaerr** [comment]
Now the annoying thing is that `requests-oauthlib==0.8` (bundled with Ubuntu 18.04) doesn't support `include_client_id`:
https://github.com/requests/requests-oauthlib/blob/v0.8.0/requests_oauthlib/oauth2_session.py#L155

But it does seem to support `client_id`! So you might be right, I just need to check if it works on all supported platforms.

**Comment by gijzelaerr** [comment]
I only notice now that this breaks most of the test suite, so I've reverted the commit (for now).

**Pull request merged**
