### PR TITLE
Fix issue #269.

### PR DESCRIPTION
**Pull request by alvra**
Tested on Debian and Ubuntu.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
looking good, but is there no test to automatically verify this?

**Comment by gijzelaerr** [comment]
@amarsman does this PR solve your issue on Debian?

**Comment by amarsman** [comment]
Looks like automatic connect after selecting of a connection does no longer work now? I get into Disconnected state, e.g.:

2021-04-04 13:44:06,399 - MainThread - INFO - eduvpn.nm - nm.py:135 - writing configuration to Network Manager
2021-04-04 13:44:06,399 - MainThread - INFO - eduvpn.storage - storage.py:183 - Writing configuration to /tmp/tmpv_f75yoi/eduVPN.ovpn
2021-04-04 13:44:06,407 - MainThread - INFO - eduvpn.nm - nm.py:121 - Updating existing connection with new configuration
2021-04-04 13:44:06,415 - MainThread - DEBUG - eduvpn.nm - nm.py:112 - Connection updated for uuid: 9518b1e2-df2c-443a-a4e6-8c3a5c6629ad, result: True, remote_con: <NM.RemoteConnection object at 0x7f98ac420b40 (NMRemoteConnection at 0x1c1eb20)>
2021-04-04 13:44:06,415 - MainThread - INFO - eduvpn.interface.event - event.py:166 - Finished saving network manager config: <Gio.SimpleAsyncResult object at 0x7f98ac3c73f0 (GSimpleAsyncResult at 0x1efaeb0)>
2021-04-04 13:44:06,415 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <ConfiguringConnection server=<InstituteAccessServer 'Demo'>> -> finished_configuring_connection
2021-04-04 13:44:06,422 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: finished_configuring_connection -> <ConnectionStatus server=<InstituteAccessServer 'Demo'>, validity=<eduvpn.crypto.Validity object at 0x7f98ac3c6e48>>
2021-04-04 13:44:06,423 - MainThread - INFO - eduvpn.app - app.py:111 - network transitioning: <ConnectedState> -> start_new_connection
2021-04-04 13:44:06,423 - MainThread - DEBUG - eduvpn.nm - nm.py:187 - deactivate_connection uuid: 9518b1e2-df2c-443a-a4e6-8c3a5c6629ad connection: <NM.VpnConnection object at 0x7f98ad6ded38 (NMVpnConnection at 0x18825a0)>
2021-04-04 13:44:06,423 - MainThread - INFO - eduvpn.nm - nm.py:162 - activate_connection uuid: 9518b1e2-df2c-443a-a4e6-8c3a5c6629ad connection: <NM.RemoteConnection object at 0x7f98ac420b40 (NMRemoteConnection at 0x1c1eb20)>
2021-04-04 13:44:06,428 - MainThread - INFO - eduvpn.app - app.py:122 - network transitioned: start_new_connection -> <ConnectingState>
2021-04-04 13:44:06,428 - MainThread - ERROR - eduvpn.nm - nm.py:175 - nm-manager-error-quark: Connection 'eduVPN' is already active (6)
2021-04-04 13:44:06,429 - MainThread - INFO - eduvpn.app - app.py:111 - network transitioning: <ConnectingState> -> set_connected
2021-04-04 13:44:06,436 - MainThread - INFO - eduvpn.app - app.py:122 - network transitioned: set_connected -> <ConnectedState>
2021-04-04 13:44:06,437 - MainThread - INFO - eduvpn.nm - nm.py:198 - deactivate_connection_async result: True
2021-04-04 13:44:06,438 - MainThread - INFO - eduvpn.app - app.py:111 - network transitioning: <ConnectedState> -> set_disconnected
2021-04-04 13:44:06,450 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:575 - on_activate_changed
2021-04-04 13:44:06,450 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <ConnectionStatus server=<InstituteAccessServer 'Demo'>, validity=<eduvpn.crypto.Validity object at 0x7f98ac3c6e48>> -> deactivate_connection
2021-04-04 13:44:06,450 - MainThread - INFO - eduvpn.app - app.py:111 - network transitioning: <DisconnectedState> -> disconnect
2021-04-04 13:44:06,450 - MainThread - ERROR - eduvpn.app - app.py:118 - invalid network state transition: <DisconnectedState> -> disconnect
2021-04-04 13:44:06,466 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: deactivate_connection -> <ConnectionStatus server=<InstituteAccessServer 'Demo'>, validity=<eduvpn.crypto.Validity object at 0x7f98ac3c6e48>>
2021-04-04 13:44:06,467 - MainThread - INFO - eduvpn.app - app.py:122 - network transitioned: set_disconnected -> <DisconnectedState>

**Comment by alvra** [comment]
I believe the last commit addresses the problem @amarsman mentioned.

**Comment by gijzelaerr** [comment]
@amarsman does this solve your issue? I'll create a debian VM to verify also.

**Pull request merged**
